version: '3.8'

services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud:28.0.5
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: 123456qwerty
    volumes:
      - ./nextcloud:/var/www/html
    networks:
      - nextcloud_network

  nginx:
    container_name: nginx
    depends_on:
      - nextcloud
    image: nginx:1.25.4
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge
