version: '3'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/openvpn:/etc/openvpn
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - OPENVPN_CONFIG=udp://93.183.74.90

  easyrsa:
    image: kylemanna/openvpn
    container_name: easyrsa
    volumes:
      - /opt/openvpn:/etc/openvpn
    stdin_open: true
    tty: true
    command: easyrsa build-client-full myclient nopass

  ovpn_getclient:
    image: kylemanna/openvpn
    container_name: ovpn_getclient
    volumes:
      - /opt/openvpn:/etc/openvpn
    entrypoint: ["ovpn_getclient", "myclient"]
    command: >-
      /bin/sh -c "cat > /etc/openvpn/myclient.ovpn && chown $(stat -c '%u:%g' /etc/openvpn/myclient.ovpn) /etc/openvpn/myclient.ovpn"

