version: '3.8'

services:

  mysql:
    container_name: mysql
    image: mysql:oraclelinux8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    image: wordpress:php8.1-apache
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress_network

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx:1.25.4
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
